apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chaos-target.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "chaos-target.name" . }}
    helm.sh/chart: {{ include "chaos-target.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  MIN_DELAY_MS: {{ .Values.chaos.minDelayMs | quote }}
  MAX_DELAY_MS: {{ .Values.chaos.maxDelayMs | quote }}
  BURN_CPU: {{ .Values.chaos.burnCpu | quote }}
  CPU_COMPLEXITY: {{ .Values.chaos.cpuComplexity | quote }}
  EXTERNAL_SERVICES: {{ .Values.chaos.externalServices | quote }}
  MAX_CALL_DEPTH: {{ .Values.chaos.maxCallDepth | quote }}
  REQUEST_TIMEOUT: {{ .Values.chaos.requestTimeout | quote }}
